src/components/locale-switch.vue
- removes watchEffect in locale-switch
- adds computed property instead
- resolves #4
=> fix [locale-switch.vue]: resolves #4

src/pages/documentation/[...slug].vue, src/pages/index.vue, src/pages/search.vue
- wrapped page meta in t() function
- page meta now updates on lang-switch
-  resolves #5
=> fix: i18nalize page meta

components/app-header.vue, components/download-menu.vue, components/indicator.vue, components/locale-switch.vue, components/range-slider.vue, components/xlsx-button.vue, lib/facets.ts, locales/de.json, locales/en.json, package.json, pages/detail/courts/[id].vue, pages/detail/institutions/[id].vue, pages/detail/persons/[id].vue, pages/detail/places/[id].vue, pages/search.vue, pages/search/courts.vue, pnpm-lock.yaml, types/schema.d.ts
resolves #46, resolves #71, resolves #72
=> Feat  xlsx and time spans

components/range-slider.vue, lib/facets.ts, locales/de.json, locales/en.json, pages/detail/persons/[id].vue, pages/search.vue, types/schema.d.ts
=> More feedback features

components/autocomplete.vue, components/search-table.vue, pages/detail/courts/[id].vue, pages/detail/events/[id].vue, pages/detail/institutions/[id].vue, pages/detail/persons/[id].vue, pages/detail/places/[id].vue, pages/documentation/[...slug].vue, pages/hierarchy.vue, pages/index.vue, pages/search.vue, pages/search/courts.vue, pages/search/events.vue, pages/search/institutions.vue, pages/search/persons.vue, pages/search/places.vue, pages/search/references.vue, pages/search/relations.vue
=> small optimizations, added titles

components/content/header-wrapper.vue, locales/de.json, locales/en.json, pages/detail/persons/[id].vue, pages/hierarchy.vue, types/schema.d.ts
resolves #90
resolves #89
resolves #88
resolves #87
=> New-issues-20.03

components/detail-page.vue, locales/de.json, pages/detail/persons/[id].vue
=> resolves #100, changed detail layout a bit

.github/workflows/playwright.yml, components/info-menu.vue, pages/detail/persons/[id].vue
=> April issues pt3

components/hierarchy-link-button.vue, locales/de.json, locales/en.json, pages/detail/persons/[id].vue
resolves #112
resolves #114
resolves #117
resolves #99
=> May issues

components/app-header.vue, components/facet-field.vue, components/generic-listbox.vue, components/loading-bar.vue, components/locale-switch.vue, components/search-table.vue, pages/detail/courts/[id].vue, tailwind.config.ts, types/schema.d.ts
resolves #120
resolves #121
resolves #122
resolves #123
resolves #124
=> May issues pt2

components/app-header.vue, components/facet-field.vue, components/generic-listbox.vue, components/loading-bar.vue, components/locale-switch.vue, components/search-table.vue, pages/detail/courts/[id].vue, tailwind.config.ts, types/schema.d.ts
resolves #120
resolves #121
resolves #122
resolves #123
resolves #124
---------
=> May issues pt2 (#125)

components/detail-disclosure.vue, locales/de.json, locales/en.json, package.json, pages/detail/persons/[id].vue, pnpm-lock.yaml, types/schema.d.ts
sadly the issues this resolves have not been created ;_;
=> Notes and dates

components/search-table.vue, lib/helpers.ts, pages/detail/courts/[id].vue, pages/detail/institutions/[id].vue, pages/detail/persons/[id].vue, pages/detail/places/[id].vue, pages/search/courts.vue, pages/search/events.vue, pages/search/institutions.vue, pages/search/persons.vue, pages/search/places.vue, pages/search/relations.vue
resolves  #145, resolves #146, resolves #115
=> resolves  #145, resolves #146, resolves #115

components/search-table.vue, lib/helpers.ts, pages/detail/courts/[id].vue, pages/detail/institutions/[id].vue, pages/detail/persons/[id].vue, pages/detail/places/[id].vue, pages/search/courts.vue, pages/search/events.vue, pages/search/institutions.vue, pages/search/persons.vue, pages/search/places.vue, pages/search/relations.vue
=> Add. bugfixing

app/(app)/search/_components/status-indicator.tsx, styles/index.css
this ensures that colors for the status indicator are included.
fixes #171
=> fix: include status indicator colors

app/(app)/courts/[id]/page.tsx, app/(app)/institutions/[id]/page.tsx, app/(app)/persons/[id]/page.tsx, app/(app)/places/[id]/page.tsx, components/download-menu.tsx, messages/de.json
needs clarifications which relations should be included.
closes #172 
check:
=> feat: include relations in excel download

app/sitemap.ts
this pr adds sitemap entries for all details pages.
closes #185
=> feat: add sitemap

app/(app)/search/layout.tsx
=> feat: add tooltips to disabled links

app/(app)/persons/[id]/_lib/data.ts, app/(app)/persons/[id]/page.tsx
=> fix: add cause of death

app/(app)/courts/[id]/page.tsx, app/(app)/institutions/[id]/page.tsx, app/(app)/persons/[id]/page.tsx, app/(app)/places/[id]/page.tsx
this fixes redirecting to the 404 page on missing items in typesense details collections.
=> fix: fix not-found errors
